# Site settings
title:          Mukul Kumar
description:    "My personal webspace"
baseurl:        
url:            "https://mukulkumar22.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X


# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

minima:
  social_links:
    twitter: rohan__rajpal
    github: rohanrajpal
    instagram: rohan__rajpal
    linkedin: rohanrajpal
    rss: rss
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme